### ISSUE TITLE
Alerta de vírus ao instalar via NPM

### ISSUE THREAD

**Issue by sandrosimas** [efipay/js-payment-token-efi#2]
Recebi este alerta pelo anti vírus Bitdefender (MacOS) ao instalar a biblioteca `payment-token-efi` pelo yarn (https://www.npmjs.com/package/payment-token-efi#node). Poderiam verificar?

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/bf1726a5-0d72-4472-8408-5799c05a61e9">

**Comment by guilherme-cota-efi** [comment]
Olá, @sandrocsimas. Tudo bem?
Acreditamos que isso pode ser um falso positivo do antivírus. No print, vemos que a instalação é da versão 2.1.0 da biblioteca. Lançamos uma nova versão recentemente. Tente instalar novamente, por favor.
